"""Makes the FORScan pages of the wiki (docs/wiki/FORScan-*.md) from the FORScan
PID catalogue that openRS_ bundles (android/app/src/main/assets/pids/forscan_modules.json).

    python dev/make_wiki_forscan.py                       # fetches the catalogue from GitHub
    python dev/make_wiki_forscan.py path/to/forscan_modules.json

The catalogue is the PID list FORScan shows for a Focus RS Mk3, grouped by module. It has
names, descriptions and units for every PID, but a diagnostic address (DID) and a formula
only for the few that openRS_ polls itself, so the pages show those where there are any.

Writes FORScan-PIDs.md (the index and the PIDs with a known DID), FORScan-PCM.md,
FORScan-BCM.md, FORScan-IPC.md and FORScan-Other-Modules.md. Re-run it when openRS_'s
catalogue changes; don't edit those files by hand.

The catalogue is MIT licensed (https://github.com/klexical/openRS_), and the pages say so.
Uses only the standard library.
"""

import json
import sys
import urllib.request
from pathlib import Path

DEV = Path(__file__).resolve().parent
OUT_DIR = DEV.parent / "docs" / "wiki"
SOURCE_URL = "https://raw.githubusercontent.com/klexical/openRS_/main/android/app/src/main/assets/pids/forscan_modules.json"
SOURCE_PAGE = "https://github.com/klexical/openRS_/blob/main/android/app/src/main/assets/pids/forscan_modules.json"

# Pages with a module of their own; every other module goes on FORScan-Other-Modules
OWN_PAGES = {"PCM": "FORScan-PCM", "BCM": "FORScan-BCM", "IPC": "FORScan-IPC"}
OTHER_PAGE = "FORScan-Other-Modules"
PAGE_LABELS = {"FORScan-PCM": "PCM page", "FORScan-BCM": "BCM page", "FORScan-IPC": "IPC page",
               OTHER_PAGE: "Other modules"}

NOTE = ("<!-- Generated by dev/make_wiki_forscan.py from openRS_'s forscan_modules.json. "
        "Don't edit by hand; re-run the script. -->")


def load(source):
    if source.startswith("http"):
        with urllib.request.urlopen(source) as response:
            return json.loads(response.read().decode("utf-8"))
    return json.loads(Path(source).read_text(encoding="utf-8"))


def clean(text, degree_sign=False):
    """Table-safe text. The catalogue has a replacement character where its units had a degree sign."""
    text = (text or "").strip()
    if degree_sign:
        text = text.replace("�", "°")
    return text.replace("�", "").replace("|", "\\|").replace("<", "&lt;").replace(">", "&gt;")


def unique_pids(module):
    """The module's PIDs sorted by name, with exact repeats (FORScan lists some twice) dropped."""
    seen = set()
    rows = []
    for pid in sorted(module["pids"], key=lambda p: (p["name"].lower(), p["description"].lower())):
        key = (pid["name"], pid["description"], pid.get("unit", "").strip())
        if key in seen:
            continue
        seen.add(key)
        rows.append(pid)
    return rows


def module_section(module, level):
    """The module's heading, its address and a table of its PIDs."""
    pids = unique_pids(module)
    has_did = any("did" in p for p in pids)
    lines = ["#" * level + " %s - %s" % (module["id"], module["name"]), ""]

    details = ["%d PIDs" % len(pids)]
    if len(pids) != module["pid_count"]:
        details[0] += " (%d listed; exact repeats merged)" % module["pid_count"]
    if "can_request_id" in module:
        details.append("diagnostic request `%s`, response `%s`" % (module["can_request_id"], module["can_response_id"]))
    lines += [", ".join(details) + ".", ""]

    header = "| PID | Description | Unit |" + (" DID |" if has_did else "")
    lines += [header, "|---|---|---|" + ("---|" if has_did else "")]
    for pid in pids:
        row = "| `%s` | %s | %s |" % (clean(pid["name"]), clean(pid["description"]), clean(pid.get("unit"), True))
        if has_did:
            row += " %s |" % ("`%s`" % pid["did"] if "did" in pid else "")
        lines.append(row)
    lines.append("")
    return lines


def footer():
    return ["---", "",
            "PID names, descriptions and units are FORScan's, as bundled by "
            "[openRS_](https://github.com/klexical/openRS_) (MIT licence) in "
            "[forscan_modules.json](%s). See [Sources and Credits](Sources-and-Credits.md)." % SOURCE_PAGE, ""]


def write(name, lines):
    (OUT_DIR / (name + ".md")).write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print("wrote docs/wiki/%s.md" % name)


def index_page(catalogue, modules):
    lines = [NOTE, "", "# FORScan PIDs", "",
             "FORScan lists {:,} PIDs for the Focus RS Mk3 across {} modules. The names, descriptions and units "
             "are on the module pages below; **the diagnostic address (DID) is known for only {} of them**, "
             "the ones openRS_ marks as monitored. To read any other one you need its DID, see "
             "[Finding and Confirming PIDs](Finding-and-Confirming-PIDs.md).".format(
                 catalogue["total_pids"], len(modules), catalogue["monitored_pids"]), "",
             "## Modules", "",
             "| Module | Name | PIDs | Request / response | Page |", "|---|---|---|---|---|"]
    for module in modules:
        page = OWN_PAGES.get(module["id"], OTHER_PAGE)
        address = "`%s` / `%s`" % (module["can_request_id"], module["can_response_id"]) if "can_request_id" in module else ""
        lines.append("| %s | %s | %d | %s | [%s](%s.md) |" % (
            module["id"], module["name"], len(unique_pids(module)), address, PAGE_LABELS[page], page))
    lines += ["", "PID counts have exact repeats merged. Modules with no address listed are in the catalogue "
              "without one; their addresses aren't in the sources yet.", "",
              "## PIDs with a known DID", "",
              "Formulas use `A` for the first data byte after the DID and `B` for the second. "
              "\"openRS_ field\" is the name openRS_ stores the value under. A blank formula means the "
              "catalogue has none; [Diagnostic DIDs](Diagnostic-DIDs.md) has the formulas openRS_ uses for the "
              "tyre pressures, sensor IDs and odometer.", "",
              "The Unit column is FORScan's, and openRS_'s formula doesn't always produce it: `FRP` is stored "
              "in psi (`hpFuelRailPsi`), and the boost (`TCBP`, `TCBP_DSD`), throttle (`ETC_ACT`, `ETC_DSD`) "
              "and wastegate formulas are labelled with different units or sizes in different openRS_ files. "
              "See \"Where the sources disagree\" on the [Diagnostic DIDs](Diagnostic-DIDs.md) page.", "",
              "| Module | PID | Description | DID | Bytes | Formula | Unit | openRS_ field |",
              "|---|---|---|---|---|---|---|---|"]
    for module in modules:
        for pid in unique_pids(module):
            if pid.get("status") != "monitored":
                continue
            lines.append("| %s | `%s` | %s | `%s` | %s | %s | %s | %s |" % (
                module["id"], clean(pid["name"]), clean(pid["description"]), pid["did"],
                pid.get("bytes", ""), "`%s`" % pid["formula"] if "formula" in pid else "",
                clean(pid.get("unit"), True), "`%s`" % pid["field"] if "field" in pid else ""))
    lines.append("")
    return lines + footer()


def main():
    source = sys.argv[1] if len(sys.argv) > 1 else SOURCE_URL
    catalogue = load(source)
    modules = catalogue["modules"]
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    write("FORScan-PIDs", index_page(catalogue, modules))

    for module in modules:
        if module["id"] in OWN_PAGES:
            write(OWN_PAGES[module["id"]], [NOTE, "", *module_section(module, 1), *footer()])

    others = [m for m in modules if m["id"] not in OWN_PAGES]
    lines = [NOTE, "", "# FORScan PIDs: the other modules", "",
             "ABS, AWD, power steering, doors, climate, restraints and the rest. The engine computer, body "
             "module and instrument cluster have their own pages: [PCM](FORScan-PCM.md), [BCM](FORScan-BCM.md) "
             "and [IPC](FORScan-IPC.md).", ""]
    for module in others:
        lines.append("- [%s - %s](#%s)" % (module["id"], module["name"], anchor(module)))
    lines.append("")
    for module in others:
        lines += module_section(module, 2)
    write(OTHER_PAGE, [*lines, *footer()])


def anchor(module):
    """GitHub's anchor for the heading module_section writes: lower case, punctuation dropped, spaces to dashes."""
    heading = "%s - %s" % (module["id"], module["name"])
    kept = "".join(c for c in heading.lower() if c.isalnum() or c in " -_")
    return kept.replace(" ", "-")


if __name__ == "__main__":
    main()
